AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/NumericPredicate:
  Exclude:
    - lib/tar/backports.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
