AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/rake

Lint/NestedMethodDefinition:
  Exclude:
    - test/file_reader_test.rb
    - test/writer_test.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
